### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by Vandergui** [DiegoChuW/RSItradingBot#2]
I was looking for one for RSI divergences, I found yours and I would like to test RSItradingBot on Ninja Trader 8, but it is giving me this error "This NinjaScript file was created from an incompatible version of Ninja Trader".

**Comment by DiegoChuW** [comment]
I have version 8.0.27.1 but it should also work with the newer versions. Maybe try recompiling it in an older version to see if that works. 

If you have an even older version try updating it and restarting your app.

**Comment by Vandergui** [comment]
Thanks for the quick response
I compiled it and it worked but it's not making the entries or is that the case, the entries are manual?

> Tenho a versão 8.0.27.1, mas também deve funcionar com as versões mais recentes. Talvez tente recompilá-lo em uma versão mais antiga para ver se funciona.
> 
> Se você tiver uma versão ainda mais antiga, tente atualizá-la e reiniciar o aplicativo.



> Tenho a versão 8.0.27.1, mas também deve funcionar com as versões mais recentes. Talvez tente recompilá-lo em uma versão mais antiga para ver se funciona.
> 
> Se você tiver uma versão ainda mais antiga, tente atualizá-la e reiniciar o aplicativo.

**Comment by DiegoChuW** [comment]
The entries aren't supposed to be manual but you must have it connected to some sort of data when you backtest it. If you do have it connected to some data and its not making any entries then it could just be the case that no trades were made because the bot is too conservative. You would want to backtest it with something thats really volatile and on the 1 minute candles where high moves occur. 

For example, I was using Coinbase when I backtested the trading bot. When you run it you will be able to see how many and when the trades were made. However, it may not always make a trade depending on the data that you give it. You can always configure this according to your data type but that's how I was able to make use of it. 

Hope this helps.
